### ISSUE TITLE
Sort order of numeric values is a bit screwy

### ISSUE THREAD

**Issue by MikeEvans** [micz/ColumnsWizard#29]
![x-spam-score](https://cloud.githubusercontent.com/assets/2635196/7879183/06487ce4-05e6-11e5-8459-d4de62173763.PNG)

It looks like it strips off the negative and sorts the rest as a string to me.

**Comment by micz** [comment]
It's needed to add a new option for a custom column that let the user choose to sort it as a number.
In mzcw-overlay.js it has to be used the `unsigned long getSortLongForRow(in nsIMsgDBHdr aHdr);` function instead of the current one: https://github.com/micz/ColumnsWizard/blob/3c50a8ef9248cc90ac121a49c364176e9a538d20/chrome/content/mzcw-overlay.js#L100 .

More info: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIMsgCustomColumnHandler#getSortStringForRow()

**Comment by micz** [comment]
This bugfix will be released in version 5.0.3.
