### ISSUE TITLE
Unable to create sortable columns on DSPAM headers

### ISSUE THREAD

**Issue by robinsmidsrod** [micz/ColumnsWizard#55]
I've tried to create columns for these two headers injected by DSPAM into each message in my inbox, but they just show up as blank columns when I use number or alphabetical sorting.

    X-DSPAM-Confidence: 0.9899
    X-DSPAM-Probability: 1.0000

I do notice that they have 4 decimals, but that shouldn't stop them from being shown when using normal alphabetical sort.

Also, it would be nice to have support for more than 3 decimals so that these columns can be sorted properly as numbers.

Using version 6.0.3 on TB 45.1.1 in Windows 10 x64.

**Comment by micz** [comment]
I've tried to add those headers in a mail and they are correctly shown by Thunderbird.

Remember that the columns will have a value only for the mails received after you've added the custom columns to Thunderbird, because Thunderbird needs to index them in its database.
If you're using an IMAP account, you could move a mail to a new folder and then you should see the values in the custom columns.

The columns are also sorted as numbers.
To add one more decimal I need to divide by 10 the max number allowed in the field. Maybe it could be more useful to have on more decimal, I've added issue #56.

Feel free to reopen this issue if needed.

**Comment by robinsmidsrod** [comment]
@micz Thanks for the insight on how indexing affects display of old messages. I have seen the column data on new messages that have arrived.
